version: '3.7'
services:
  app:
    container_name: docker-node-app
    depends_on:
      - db
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile-dev    
    volumes:
      - ../../:/home/app/app
    environment:
      - NODE_ENV=development  
      - DATABASE_URL=postgres://user:pass@db:5432/db  
      - PORT=5000
    ports:
      - "5000:5000"
  db:
    container_name: db
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db

