version: '3.7'
services:
  app:
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile-dev    
    volumes:
      - ../../:/home/app/app
    environment:
      - NODE_ENV=development    
    ports:
      - "5000:5000"
      - "9229:9229"