# docker-compose.yml
version: "3"
services:
  app:
    container_name: docker-node-app
    depends_on:
      - postgres
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile-dev    
    volumes:
      - ../../:/home/app/app
    environment:
      - NODE_ENV=development  
      - DATABASE_URL=postgres://user:pass@postgres:5432/db  
      - PORT=3000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

# version: '3.7'
# services:
#   app:
#     container_name: docker-node-app
#     depends_on:
#       - db
#     build:
#       context: ../../
#       dockerfile: docker/app/Dockerfile-dev    
#     volumes:
#       - ../../:/home/app/app
#     environment:
#       - NODE_ENV=development  
#       - DATABASE_URL=postgres://user:pass@postgres:5432/db  
#       - PORT=5000
#     ports:
#       - "5000:5000"
#   db:
#     image: postgres:10.4
#     ports:
#       - "35432:5432"
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD= pass
#       - POSTGRES_DB= db

